name: Python Unit Tests

on: 
    push:
        branches: [ main ]
    pull_request:
        branches: [ main ]

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            #Step 1:  to check out the code
            - name: Checkout code
              uses: actions/checkout@v2 # Check out the repository code
            #Step 2: Set up Python environment
            - name: Set up Python
              uses: actions/setup-python@v2
              with:
                    python-version: '3.8' # Specify the Python version to use
            #Step 3: Install dependencies
            - name: Install dependencies
              run:
                    python -m pip install --upgrade pip
                    pip install -r requirements.txt # Install the dependencies from requirements.txt
            #Step 4: Run tests
            - name: Run tests
              run:
                    pytest tests/ # Run the tests located in the tests directory
